name: build docker images

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-push-frontend:
    name: 'Build and push frontend'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./runregistry_frontend/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/386
          push: true
          tags: cmssw/runregistry-frontend:latest

  # build-and-push-backend:
  #   name: 'Build and push backend'
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v1
  #     - uses: whoan/docker-build-with-cache-action@v5
  #       with:
  #         username: fabioespinosa
  #         password: ${{ secrets.DOCKER_HUB_PASSWORD }}
  #         image_name: cmssw/runregistry-backend
  #         tags: latest,${{ github.sha }}
  #         context: ./runregistry_backend
  #         pull_image_and_stages: false
  #         dockerfile: Dockerfile

  # build-and-push-dqm-gui-pinging:
  #   name: 'Build and push DQM GUI pinging'
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v1
  #     - uses: whoan/docker-build-with-cache-action@v5
  #       with:
  #         username: fabioespinosa
  #         password: ${{ secrets.DOCKER_HUB_PASSWORD }}
  #         image_name: cmssw/runregistry-workers-dqm-gui-pinging
  #         tags: latest,${{ github.sha }}
  #         context: ./runregistry_backend
  #         pull_image_and_stages: false
  #         dockerfile: DockerfilePingGUI
