name: build docker images

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-push-frontend:
    name: 'Build and push frontend'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./runregistry_frontend
          file: ./runregistry_frontend/Dockerfile
          push: true
          tags: cmssw/runregistry-frontend:latest

  build-and-push-backend:
    name: 'Build and push backend'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./runregistry_backend
          file: ./runregistry_backend/Dockerfile
          push: true
          tags: cmssw/runregistry-backend:latest

  build-and-push-dqm-gui-pinging:
    name: 'Build and push microservice for GUI pinging'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./runregistry_backend
          file: ./runregistry_backend/DockerfilePingGUI
          push: true
          tags: cmssw/runregistry-workers-dqm-gui-pinging:latest
